### ISSUE TITLE
DropdownItem page navigation.

### ISSUE THREAD

**Issue by hammie1010** [Blazorade/Blazorade-Bootstrap#108]
Should the following DropdownItem route to a page component assuming it exists?

`                <DropdownNavItem Text="Dropdown">
                    <DropdownItem Text="Item #1" Url="somepage" />
                </DropdownNavItem>
`

**Comment by MikaBerglund** [comment]
Yes it should. Seems that there is a bug that I managed to reproduce in the [Showroom application](https://www.blazorade.com/Blazorade-Bootstrap/). The "Resources" dropdown menu item to the right is created just like your sample with the difference that it opens in a new tab. The new tab opens, but the link is not loaded.

The code for that main menu is found [here](https://github.com/Blazorade/Blazorade-Bootstrap/blob/master/Blazorade.Bootstrap.Components.Showroom/Host/Shared/MainMenu.razor#L57). I guess it's pretty much the same as your code?

I'll file this as a bug and set it to be fixed in the first release.

**Comment by hammie1010** [comment]
Yes, that is equivalent.  Sounds great - thanks.

**Comment by MikaBerglund** [comment]
Was actually quite an easy fix. I already have a PR #109 with the fix for this. I'll process that and publish a fixed Nuget package also. It should be available shortly.

**Comment by MikaBerglund** [comment]
The fix to this is now [published on Nuget](https://www.nuget.org/packages/Blazorade.Bootstrap.Components/0.12.1-preview).

**Comment by MikaBerglund** [comment]
Thanks for reporting!
