### ISSUE TITLE
publish blazorade _content to <base href="/myroot/">

### ISSUE THREAD

**Issue by ghstahl** [Blazorade/Blazorade-Bootstrap#189]
https://github.com/javiercn/BlazorMultipleApps
I am using the above starter project as a baseline to add Blazorade.  I want to have the ability to have 2 different blazor apps that have their own stacks.  So different version of the blazorade components.

You can see for the [index.html](https://github.com/javiercn/BlazorMultipleApps/blob/master/BlazorMultipleApps/SecondClient/wwwroot/index.html) that context is given using the following;
```
 <base href="/SecondApp/" />
```
The following entry is actually pulled from ```/SecondApp/_framework/blazor.webassembly.js```
```
<script src="_framework/blazor.webassembly.js"></script>
```
The way the publish knows what folder to put it into is in the [SecondBlazorApp.Client.csproj]( https://github.com/javiercn/BlazorMultipleApps/blob/master/BlazorMultipleApps/SecondClient/SecondBlazorApp.Client.csproj)  using the ```<StaticWebAssetBasePath>SecondApp</StaticWebAssetBasePath>```   

```
<PropertyGroup>
    <StaticWebAssetBasePath>SecondApp</StaticWebAssetBasePath>
</PropertyGroup>
```
so context is preserved.
when I add the following;
```
    <script src="_framework/blazor.webassembly.js"></script>
    <script src="_content/Blazorade.Bootstrap.Components/bbs.js"></script>
```
there is no  ```/SecondApp/_content/Blazorade.Bootstrap.Components/bbs.js```

That is the context I need because different blazor project are using different versions of the blazorade library.

As it is now, if I have 2 blazor clientside apps that have diffferent versions of blazorade they will collide in the final publish of the hosting app.

The expectation would be that component libraries honor csproj directive;
```
<StaticWebAssetBasePath>SecondApp</StaticWebAssetBasePath>
```

**Comment by MikaBerglund** [comment]
I will look into this one and see if there's something we can do about it.

**Comment by MikaBerglund** [comment]
Hello!

I've now looked into this. Everything should work just fine also with Blazorade Bootstrap. In fact, the [client test host application](https://github.com/Blazorade/Blazorade-Bootstrap/tree/master/ClientTestHost) that you find in the repository for Blazorade Bootstrap, is configured to run in the `/Blazorade-Bootstrap/` subdirectory.

The startup parameters for this configuration are not included in the source code, since they are in the `launchSettings.json` file that is by default excluded. However, if you run it locally in IIS Express and specify the command line argument `--contentRoot=/Blazorade-Bootstrap`, it should work as expected.

The bbs.js script file is now loaded from `/Blazorade-Bootstrap/_content/Blazorade.Bootstrap.Components/bbs.js` and not `/_content/Blazorade.Bootstrap.Components/bbs.js`.

Remember also that the script reference must not start with a forward slash, so the script tag should look like this.

`<script src="_content/Blazorade.Bootstrap.Components/bbs.js"></script>`

Also have a look at the [`index.html`](https://github.com/Blazorade/Blazorade-Bootstrap/blob/master/ClientTestHost/wwwroot/index.html) file that defines the base URL and references the script file.

I'll close this issue now, but if you still think that there's something that needs to be implemented in Blazorade Bootstrap, please feel free to add more comments here.
