### ISSUE TITLE
Why Javascript?

### ISSUE THREAD

**Issue by user72356** [Blazorade/Blazorade-Bootstrap#190]
This is not an issue but more of a suggestion or even a rambling. I'm new to Blazor AND Bootstrap. However, a big thing I like about Blazor is that you can basically throw Javascript out the window. But using some of Bootstrap's components, you're forced to bring JS back in because that's what Bootstrap needs. Now would it be possible to design Bootstrap razor components that do not use JS but instead make use of Blazor native DOM manipulation functions? Maybe that's what Telerik's Blazor UI does, not sure?

**Comment by MikaBerglund** [comment]
Perhaps it would be possible to use Bootstrap in Blazor without using JavaScript, but that would probably also require a lot of code to be written.

The approach we've taken with Blazorade Bootstrap is that we use the Bootstrap JavaScript APIs inside of the components we have in the library, so that you as a developer don't have to bother with JavaScript at all. You just [set up the library](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Getting-Started) in your Blazor application, and you can forget about JavaScript after that. Our goal is to enable to you write rich Bootstrap applications without a single line of JavaScript code when you use Blazorade Bootstrap.

**Comment by user72356** [comment]
Thank you for your reply
