### ISSUE TITLE
Blazorade and Bootstrap Template

### ISSUE THREAD

**Issue by jcrwks** [Blazorade/Blazorade-Bootstrap#25]
I am trying to get blazorade working with a template I downloaded for bootstrap and when I click on the hamburger menu the menu pops up but when I click outside the menu it does not disappear.

Any ideas?

Thanks,
Joe Harmon
jharmon@blinfo.com

**Comment by MikaBerglund** [comment]
Hi Joe! Thanks for reporting.

This is actually how the [Bootstrap Navbar](https://getbootstrap.com/docs/4.4/components/navbar/) works, so there's nothing wrong with your code.

However, that have me an idea. We could actually implement this in the [`Navbar`](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Navbar) and [`Collapse`](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Collapse) components (the `Navbar` uses the `Collapse` component internally) as a switch parameters, so you could just switch it on or off.

I'll create another issue for this, so we can then schedule that for a future version. We'll probably not include it in [v1.0](https://github.com/Blazorade/Blazorade-Bootstrap/wiki/Release-v1.0), since that is more or less laid out already.

I will link that issue here after creating it and close this issue.

**Comment by MikaBerglund** [comment]
This new feature is now described in #26 so I'll close this issue.
