### ISSUE TITLE
Blazorade Button to switch/toggle skin

### ISSUE THREAD

**Issue by jcrwks** [Blazorade/Blazorade-Bootstrap#88]
I am trying to use Blazorade with a bootstrap template that has the following code markup to switch the theme from light to dark.

``` HTML
<button class="btn btn-light btn-block text-primary " data-toggle="skin" type="button">
<span class="d-compact-menu-none">Night mode</span>
     <i class="fas fa-moon ml-1"></i>
</button>
```

I tried using the blazorade button but it does not do anything when clicked.  Should the skin switch by just clicking the button or do I need to put in a click event?  In their sample it works without a click event.

Any help appreciated....
Joe

**Comment by MikaBerglund** [comment]
If you add the `data-toggle` attribute to a Blazorade Bootstrap Button component, it should just render  as in your example. So this should be correct.

``` HTML
<Button Color="NamedColor.Light" TextColor="NamedColor.Primary" IsBlockLevel="true" data-toggle="skin">
    <span class="d-compact-menu-none">Night mode</span>
    <i class="fas fa-moon ml-1"></i>
</Button>
```

That should render the same output as in your example. However, to troubleshoot things, I would minimize the layers involved, and first try to get it to work without Blazorade. If the theme switches without Blazorade, then you don't need to have any click events or similar, because after all, Blazorade renders just standard HTML. So if it works without Blazorade, it should work with it as well.

Does your code sample work and does it switch the theme?

**Comment by jcrwks** [comment]
If I run their theme example which is not in blazor it works.  When I try to run in blazor with blazorade it does not work.

It does not work with the standard button either but that is why I’m trying to use blazorade for bootstrap by itself has issues when running within blazor.

**Comment by MikaBerglund** [comment]
That probably has to do with that Blazor does not know what it means to change a Bootstrap theme, so you probably have to do a click event handler in which you do something else.

But, if you could point me to the theme, I could have a look at how to make it work with Blazor and Blazorade Bootstrap. If the theme is openly available that is.

**Comment by jcrwks** [comment]
Sure check out 

Https://Themes.getbootstrap.com/preview/?thene_id=3921

**Comment by MikaBerglund** [comment]
Thanks! I'll check that.

**Comment by MikaBerglund** [comment]
It's the Looper theme, right?
https://uselooper.com/

I can only do some guessing here based on the [live demo](https://uselooper.com/) and [documentation](https://uselooper.com/docs/) for the theme, since there is no free trial version of the theme to download. Only the paid version.

When you change between dark mode and default mode, there seems to be a lot going on in the source code. The `<link />` elements linking to the CSS files for each mode are changed so that the link to the inactive mode gets an `disabled="true"` attribute. Also, the classes on the `<body>` element are changed. Finally, the live demo also seems to reload the page when you change the mode.

Typically, a Blazor application does not control the rendering if the elements in the `<head>`, nor does it control the `<body>` element, so it might require some tweaking to get the theme you picked, or any other similar theme for that matter, to work properly with Bootstrap.

I feel that this is not an issue with the theme you picked, but with themes in general, so I added a new issue about support for Bootstrap themes: #103 

For the moment I guess I'm afraid I can't help you more, but if it's OK with you, I could close this issue, and then get back to this when looking into generic support for themes as described in #103.

**Comment by jcrwks** [comment]
That’s fine.  Feel free to close I can come up with a solution through JavaScript.  I’m just trying to figure out what works and what doesn’t work when using themes with blazor and/or blazorade.  I’m not sure what should work and what shouldn’t work which is why I asked you for support.

Thanks for responding...
Joe

**Comment by MikaBerglund** [comment]
Ok. Thanks! And thank you for bringing this up. We'll take a look at it at a more generic level with issue #103.
